### ISSUE TITLE
Load small sample of sport card assets for testing & dev purposes.

### ISSUE THREAD

**Issue by bauff** [synchronizing/Sports-Portfolio#11]
Get some sample sports cards (front and back) and create a directory structure within the assets directory that makes it easy to access front and back images of the same card from the schema.

**Comment by synchronizing** [comment]
We need to make sure the schema is well generalized for _all_ cards. @timdoozy would you be able to take care of this?

**Comment by timdoozy** [comment]
The schema as of now is pretty generalized. 
/*  
    _id:                ObjectId
    playerName:         String
    team:               String
    cardDescription:    String
    sport:              String : required to be a predefined category
    imageFront:         String
    imageBack:          String
    createdAt:          xxxx-xx-xx
    updatedAt:          xxxx-xx-xx
*/

**Comment by synchronizing** [comment]
With MongoDB we can create lists, so I believe perhaps this would be a more generalized format:

```
{
    _id: ObjectId,
    card: [
        name: String,
        type: String,
        year: String,
        condition: String,
    ]
    info: [
        player: String,
        team: String,
        league: String
        sport: String,
        year: String,
        description: String,
    ],
    images: [
        front: String,
        back: String,
        other: [ ]
    ],
    createdAt: Date,
    updatedAt: Date,
}
```

The reason why I say for us to try to be more generalize is to hold more information in the table. We also need to take into consideration cards that are non-player, and cards that Rick might want to take multiple photos of. i.e.: 

![image](https://user-images.githubusercontent.com/2829082/55191389-6a213f80-5178-11e9-88cb-f0cbfebe1742.png)

Let me know your thoughts on this. @timdoozy

**Comment by timdoozy** [comment]
Wow mongo lists are pretty cool, I didn't know about lists. I think your model is a lot nicer for organizing information.

**Comment by timdoozy** [comment]
I didn't think about the case where we would need extra photos of a two sided card. I am just learning of mongo lists, and i think this is a nice way to organize the properties. I agree that we need more specific information about each card, and I think that this schema with more properties is going to give users more filtering options to search by. However I think we can change what you got and make our properties more generalized for all cards. Here is my schema, and below it are all of my notes on why I made the changes. I have been visiting multiple trading card websites trying to get a feel for what are common properties that a buyer can search by.
`
{
    _id: ObjectId,
    card: {
        set: String,
        sport: String,
        year: String,
        condition: String,
        setAmount: number,
    },
    player: {
        name: String,
        team: String,
        league: String,
        setNumber: number,
    },
    images: {
        front: String,
        back: String,
        other: [ ]
    },
    createdAt: Date,
    updatedAt: Date,
},
 `

- I moved some properties around between player and card. I also renamed "info" to be "player" of personal preference, and because the info stored inside the "player" list is about the player's card (if you know what I mean). 
- The name of a card would be the players name, and we already have that information stored under the "player" list.
- I think for "card.year" we need to account for card sets being in the format of "2011-2012", so I think leaving "card.year" as a String is good.
- I added setAmount and setNumber because it is important for trading card buyers to know this information. 
- We can always be more specific with our properties too if we want. For instance, in my schema I use "enum" to narrow the options of a property. For example I would use "enum" for "card.sport" to limit the options of this property to where it can only be a specific sport name that I predefined. However I am not sure if we could realistically do this for any other properties. 
- I commented earlier but deleted it because I thought my response wasn't thorough enough. Is this better? Thank you @synchronizing for the well researched feedback.

**Comment by timdoozy** [comment]
One more thing I forgot to mention, we previously discussed adding a property 'bought' which is a boolean variable that tracks whether or not the card has been purchased or not. This could make cleaning out the database easy by running a query to search for cards which have bought = true, then deleting them. Thoughts?

**Comment by synchronizing** [comment]
@timdoozy I agree with both of your comments. If we add the `bought` I do believe that would be more effective in keeping track of existing, and non-existing cards. Good work dude.
